dohanjun/SSGW

group/src/main/java/com/yedam/app/group/mapper/EmpMapper.java
group/src/main/java/com/yedam/app/group/service/EmpService.java
group/src/main/java/com/yedam/app/group/service/EmpVO.java
group/src/main/java/com/yedam/app/group/service/impl/EmpServiceImpl.java
group/src/main/java/com/yedam/app/group/web/EmpController.java
group/src/main/java/com/yedam/app/group/web/PersonnelContrtller.java
group/src/main/resources/mapper/group/Emp-map.xml

03-15 사원등록 컨트롤러까지만

---

group/src/main/java/com/yedam/app/group/mapper/DeptMapper.java
group/src/main/java/com/yedam/app/group/mapper/EmpMapper.java
group/src/main/java/com/yedam/app/group/service/EmpService.java
group/src/main/java/com/yedam/app/group/service/EmpVO.java
group/src/main/java/com/yedam/app/group/service/impl/EmpServiceImpl.java
group/src/main/java/com/yedam/app/group/web/EmpController.java
group/src/main/java/com/yedam/app/group/web/PersonnelContrtller.java
group/src/main/resources/mapper/group/Emp-map.xml
group/src/main/resources/mapper/group/dept-map.xml
group/src/main/resources/templates/group/personnel/empInfo.html
group/src/main/resources/templates/group/personnel/empMgmt.html
group/src/main/resources/templates/group/personnel/empinsert.html

03-17 사원등록 사원전체조회 구현 세부사항 구현중

---

group/pom.xml
group/src/main/java/com/yedam/app/group/service/impl/EmpServiceImpl.java
group/src/main/java/com/yedam/app/group/web/EmpController.java
group/src/main/resources/log4jdbc.log4j2.properties

03-18 라이브러리 log4 시큐리티 추가

---

group/src/main/java/com/yedam/app/group/service/EmpVO.java
group/src/main/java/com/yedam/app/group/service/impl/EmpServiceImpl.java
group/src/main/java/com/yedam/app/group/web/EmpController.java
group/src/main/java/com/yedam/app/group/web/PersonnelContrtller.java
group/src/main/resources/mapper/group/Emp-map.xml
group/src/main/resources/templates/group/personnel/empInfo.html
group/src/main/resources/templates/group/personnel/empUpdate.html
group/src/main/resources/templates/group/personnel/empinsert.html

03-18 사원상세 구현, 수정 구현중

---

group/src/main/java/com/yedam/app/group/service/EmpVO.java
group/src/main/java/com/yedam/app/group/web/EmpController.java
group/src/main/resources/log4jdbc.log4j2.properties
group/src/main/resources/mapper/group/Emp-map.xml
group/src/main/resources/templates/group/personnel/empMgmt.html
group/src/main/resources/templates/group/personnel/empUpdate.html
group/src/main/resources/templates/group/personnel/empinsert.html

03-19 사원등록,사원조회,상세보기,정보수정 구현완료 세부사항 하면됨

---

group/pom.xml
group/src/main/java/com/yedam/app/group/mapper/DeptMapper.java
group/src/main/java/com/yedam/app/group/mapper/EmpMapper.java
group/src/main/java/com/yedam/app/group/service/DeptService.java
group/src/main/java/com/yedam/app/group/service/DeptVO.java
group/src/main/java/com/yedam/app/group/service/EmpService.java
group/src/main/java/com/yedam/app/group/service/PasswordUtils.java
group/src/main/java/com/yedam/app/group/service/RankVO.java
group/src/main/java/com/yedam/app/group/service/RightsVO.java
group/src/main/java/com/yedam/app/group/service/impl/DeptServiceimpl.java
group/src/main/java/com/yedam/app/group/service/impl/EmpServiceImpl.java
group/src/main/java/com/yedam/app/group/web/DeptController.java
group/src/main/java/com/yedam/app/group/web/EmpController.java
group/src/main/resources/mapper/group/Emp-map.xml
group/src/main/resources/mapper/group/dept-map.xml
group/src/main/resources/templates/group/personnel/empInfo.html
group/src/main/resources/templates/group/personnel/empMgmt.html
group/src/main/resources/templates/group/personnel/empUpdate.html
group/src/main/resources/templates/group/personnel/empinsert.html

03-20 사원관리 검색,페이징기능 ,등록수정에 부서직급권한 아작스처리 수정에서 이미지 수정구현

---

group/src/main/java/com/yedam/app/group/mapper/VacationMapper.java
group/src/main/java/com/yedam/app/group/service/EmpVO.java
group/src/main/java/com/yedam/app/group/service/LeaveHistService.java
group/src/main/java/com/yedam/app/group/service/VacationVO.java
group/src/main/java/com/yedam/app/group/service/impl/LeaveHistServiceimpl.java
group/src/main/java/com/yedam/app/group/web/EmpController.java
group/src/main/resources/mapper/group/Emp-map.xml
group/src/main/resources/mapper/group/vacation-map.xml
group/src/main/resources/templates/group/personnel/empUpdate.html

03-22 퇴직처리기능 휴가자동부여 기능구현중 접근권한방식 고민중

---

group/src/main/java/com/yedam/app/GroupApplication.java
group/src/main/java/com/yedam/app/group/service/VacationScheduler.java

03-24 연차 자동부여 1시간 간격

---

group/src/main/java/com/yedam/app/group/mapper/DeptMapper.java
group/src/main/java/com/yedam/app/group/mapper/VacationMapper.java
group/src/main/java/com/yedam/app/group/service/DeptService.java
group/src/main/java/com/yedam/app/group/service/DeptVO.java
group/src/main/java/com/yedam/app/group/service/EmpService.java
group/src/main/java/com/yedam/app/group/service/EmpserchVO.java
group/src/main/java/com/yedam/app/group/service/VacationService.java
group/src/main/java/com/yedam/app/group/service/VacationVO.java
group/src/main/java/com/yedam/app/group/service/impl/DeptServiceimpl.java
group/src/main/java/com/yedam/app/group/service/impl/VacationServiceImpl.java
group/src/main/java/com/yedam/app/group/web/DeptController.java
group/src/main/java/com/yedam/app/group/web/DeptViewController.java
group/src/main/java/com/yedam/app/group/web/EmpController.java
group/src/main/java/com/yedam/app/group/web/PersonnelContrtller.java
group/src/main/java/com/yedam/app/group/web/VacationController.java
group/src/main/resources/mapper/group/Emp-map.xml
group/src/main/resources/mapper/group/dept-map.xml
group/src/main/resources/mapper/group/vacation-map.xml
group/src/main/resources/templates/group/personnel/deptMgmt.html
group/src/main/resources/templates/group/personnel/empMgmt.html
group/src/main/resources/templates/group/personnel/orgChart.html
group/src/main/resources/templates/group/personnel/vacaList.html
group/src/main/resources/templates/group/personnel/vacationList.html

03-26 휴가유형등록,유형목록조회 구현 , 연차조회 미완성 , 조직도 고치는중

---

group/src/main/resources/templates/group/personnel/orgChart.html

조직도 2번 회사에서도 나오게함

---

group/src/main/java/com/yedam/app/group/config/CustomAuthenticationSuccessHandler.java
group/src/main/java/com/yedam/app/group/service/impl/BoardServiceImpl.java
group/src/main/java/com/yedam/app/group/service/impl/FileServiceImpl.java
group/src/main/java/com/yedam/app/group/web/UserDepInfoController.java
group/src/main/java/com/yedam/app/group/web/mainController.java
group/src/main/resources/mapper/group/Emp-map.xml
group/src/main/resources/templates/common/fragments/default_header.html
group/src/main/resources/templates/group/QnA/qnaPage.html
group/src/main/resources/templates/group/mainPage.html

조성민 중간점검 20250327

---

group/src/main/java/com/yedam/app/group/mapper/DeptMapper.java
group/src/main/java/com/yedam/app/group/mapper/VacationMapper.java
group/src/main/java/com/yedam/app/group/scheduler/VacationScheduler.java
group/src/main/java/com/yedam/app/group/service/DeptService.java
group/src/main/java/com/yedam/app/group/service/VacationService.java
group/src/main/java/com/yedam/app/group/service/VacationVO.java
group/src/main/java/com/yedam/app/group/service/impl/DeptServiceimpl.java
group/src/main/java/com/yedam/app/group/service/impl/VacationServiceImpl.java
group/src/main/java/com/yedam/app/group/web/DeptController.java
group/src/main/java/com/yedam/app/group/web/DeptViewController.java
group/src/main/java/com/yedam/app/group/web/EmpController.java
group/src/main/resources/mapper/group/dept-map.xml
group/src/main/resources/mapper/group/vacation-map.xml
group/src/main/resources/templates/common/fragments/default_header.html

03-27 연차조회 관련수정

---

group/src/main/java/com/yedam/app/group/service/VacationService.java

03-27 충돌중복제거

---

group/src/main/java/com/yedam/app/group/mapper/VacationMapper.java
group/src/main/java/com/yedam/app/group/scheduler/VacationScheduler.java
group/src/main/java/com/yedam/app/group/service/VacationVO.java
group/src/main/java/com/yedam/app/group/service/impl/VacationServiceImpl.java
group/src/main/resources/mapper/group/vacation-map.xml
group/src/main/resources/templates/group/personnel/vacaList.html

03-28 연차 사용일 수정

---

group/src/main/java/com/yedam/app/group/mapper/DeptMapper.java
group/src/main/java/com/yedam/app/group/mapper/EmpMapper.java
group/src/main/java/com/yedam/app/group/service/EmpService.java
group/src/main/java/com/yedam/app/group/service/impl/EmpServiceImpl.java
group/src/main/java/com/yedam/app/group/web/DeptViewController.java
group/src/main/resources/mapper/group/Emp-map.xml
group/src/main/resources/templates/group/personnel/deptInsert.html
group/src/main/resources/templates/group/personnel/empinsert.html

03-29 부서장추가 기능구현

---

group/src/main/java/com/yedam/app/group/web/EmpController.java
group/src/main/resources/templates/group/personnel/empinsert.html

03-30 id중복검사

---

group/src/main/java/com/yedam/app/group/service/EmpService.java
group/src/main/java/com/yedam/app/group/service/impl/EmpServiceImpl.java
group/src/main/java/com/yedam/app/group/web/EmpController.java
group/src/main/resources/templates/group/personnel/empUpdate.html

03-30 pw초기화

---

group/src/main/resources/templates/group/personnel/empInfo.html
group/src/main/resources/templates/group/personnel/empUpdate.html
group/src/main/resources/templates/group/personnel/empinsert.html

03-31 등록,상세정보,수정 약간수정

---

group/src/main/java/com/yedam/app/group/config/SecurityConfig.java
group/src/main/resources/templates/common/fragments/default_sidebar.html

03-31 시큐리티 접근제한 수정

---

group/src/main/java/com/yedam/app/group/config/SecurityConfig.java
group/src/main/java/com/yedam/app/group/mapper/DeptMapper.java
group/src/main/java/com/yedam/app/group/mapper/EmpMapper.java
group/src/main/java/com/yedam/app/group/service/DeptService.java
group/src/main/java/com/yedam/app/group/service/impl/DeptServiceimpl.java
group/src/main/java/com/yedam/app/group/web/DeptViewController.java
group/src/main/resources/mapper/group/dept-map.xml
group/src/main/resources/templates/group/personnel/deptInsert.html
group/src/main/resources/templates/group/personnel/empMgmt.html
group/src/main/resources/templates/group/personnel/empinsert.html

03-31 부서삭제 구현 연결된 자료실도 삭제됨

---

group/src/main/java/com/yedam/app/group/mapper/EmpMapper.java
group/src/main/java/com/yedam/app/group/service/DeptHistVO.java
group/src/main/java/com/yedam/app/group/service/EmpVO.java
group/src/main/java/com/yedam/app/group/service/RightsVO.java
group/src/main/java/com/yedam/app/group/service/impl/DeptHistServiceImpl.java
group/src/main/resources/mapper/group/deptHist-mapper.xml
group/src/main/resources/templates/group/personnel/deptHist.html

04-02 부서이동 직책변경 html 등

---

group/src/main/resources/templates/group/personnel/deptInsert.html
group/src/main/resources/templates/group/personnel/empinsert.html
group/src/main/resources/templates/group/personnel/vacationList.html

04-03 조금수정

---

group/src/main/resources/mapper/group/dept-map.xml
group/src/main/resources/templates/group/personnel/empInfo.html
group/src/main/resources/templates/group/personnel/empUpdate.html
group/src/main/resources/templates/group/personnel/orgChart.html

04-03 html 길이제한 수정

---

group/src/main/resources/templates/common/fragments/default_sidebar.html
group/src/main/resources/templates/group/personnel/deptMgmt.html

04-04 타이틀변경

---

group/src/main/java/com/yedam/app/group/config/SecurityConfig.java
group/src/main/resources/templates/common/fragments/default_sidebar.html

04-04 최고관리자도 인사 근태 권한줌

---

group/src/main/java/com/yedam/app/group/config/AESInitializer.java
group/src/main/java/com/yedam/app/group/config/CustomAuthenticationSuccessHandler.java
group/src/main/java/com/yedam/app/group/scheduler/BasketCleanupScheduler.java
group/src/main/java/com/yedam/app/group/scheduler/MailCleanup.java
group/src/main/java/com/yedam/app/group/service/impl/ApprovalServiceImpl.java
group/src/main/java/com/yedam/app/group/service/impl/BasketServiceImpl.java
group/src/main/java/com/yedam/app/group/service/impl/DeptServiceimpl.java
group/src/main/java/com/yedam/app/group/service/impl/FileServiceImpl.java
group/src/main/java/com/yedam/app/group/web/ApprovalController.java
group/src/main/java/com/yedam/app/group/web/BoardController.java
group/src/main/java/com/yedam/app/group/web/DeptController.java
group/src/main/java/com/yedam/app/group/web/PostController.java
group/src/main/java/com/yedam/app/group/web/RepositoryController.java
group/src/main/java/com/yedam/app/group/web/ScheduleController.java
group/src/main/java/com/yedam/app/group/web/mainController.java
group/src/main/java/com/yedam/app/utill/AESKeyGenerator.java
group/src/main/java/com/yedam/app/utill/AESUtil.java
group/src/main/java/com/yedam/app/utill/AESUtilTest.java
group/src/main/java/com/yedam/app/utill/Base64Test.java
group/src/test/java/com/example/demo/Pawdtest.java

04-04 system.out 다지움

---

group/src/main/java/com/yedam/app/group/service/EmpserchVO.java
group/src/main/java/com/yedam/app/group/web/EmpController.java
group/src/main/resources/templates/group/personnel/empInfo.html
group/src/main/resources/templates/group/personnel/empMgmt.html
group/src/main/resources/templates/group/personnel/empUpdate.html

04-07 사원목록 경로수정함
